stages:
  - build

manual-build:
  variables:
    BASE_IMAGE_TAG: 1.1.1
  tags:
    - devenv
  stage: build
  script:
    - source env.sh
    - docker build -t $REGISTRY_URL$REGISTRY_URI:$BASE_IMAGE_TAG .
    - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS" https://$REGISTRY_URL

  when: manual
